import { Container, Form, FormControl } from "react-bootstrap";

const Formulario = ({ handleChange }) => {
  const categorias = [
    "business",
    "crime",
    "domestic",
    "education",
    "entertainment",
    "environment",
    "food",
    "health",
    "lifestyle",
    "other",
    "politics",
    "science",
    "sports",
    "technology",
    "top",
    "tourism",
    "world",
  ];

  const categoriasEsp = [
    "negocios",
    "crimen",
    "doméstico",
    "educación",
    "entretenimiento",
    "medio ambiente",
    "comida",
    "salud",
    "estilo de vida",
    "otro",
    "política",
    "ciencia",
    "deportes",
    "tecnología",
    "top",
    "turismo",
    "mundo",
  ];

  const nombresPaises = [
    "Afganistán",
    "Albania",
    "Argelia",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaiyán",
    "Bahamas",
    "Baréin",
    "Bangladesh",
    "Barbados",
    "Bielorrusia",
    "Bélgica",
    "Belice",
    "Benín",
    "Bermudas",
    "Bután",
    "Bolivia",
    "Bosnia y Herzegovina",
    "Botsuana",
    "Brasil",
    "Brunéi",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Camboya",
    "Camerún",
    "Canadá",
    "Cabo Verde",
    "Islas Caimán",
    "República Centroafricana",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoras",
    "Congo",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "Chipre",
    "República Checa",
    "Dinamarca",
    "Yibuti",
    "Dominica",
    "República Dominicana",
    "República Democrática del Congo",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Guinea Ecuatorial",
    "Eritrea",
    "Estonia",
    "Esuatini",
    "Etiopía",
    "Fiyi",
    "Finlandia",
    "Francia",
    "Polinesia Francesa",
    "Gabón",
    "Gambia",
    "Georgia",
    "Alemania",
    "Ghana",
    "Grecia",
    "Granada",
    "Guatemala",
    "Guinea",
    "Guyana",
    "Haití",
    "Honduras",
    "Hong Kong",
    "Hungría",
    "Islandia",
    "India",
    "Indonesia",
    "Irán",
    "Irak",
    "Irlanda",
    "Israel",
    "Italia",
    "Costa de Marfil",
    "Jamaica",
    "Japón",
    "Jersey",
    "Jordania",
    "Kazajistán",
    "Kenia",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kirguistán",
    "Laos",
    "Letonia",
    "Líbano",
    "Lesoto",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    "Macao",
    "Macedonia del Norte",
    "Madagascar",
    "Malaui",
    "Malasia",
    "Maldivas",
    "Malí",
    "Malta",
    "Islas Marshall",
    "Mauritania",
    "Mauricio",
    "México",
    "Micronesia",
    "Moldavia",
    "Mónaco",
    "Mongolia",
    "Montenegro",
    "Marruecos",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Países Bajos",
    "Nueva Zelanda",
    "Nicaragua",
    "Níger",
    "Nigeria",
    "Corea del Norte",
    "Noruega",
    "Omán",
    "Pakistán",
    "Palaos",
    "Panamá",
    "Papúa Nueva Guinea",
    "Paraguay",
    "Perú",
    "Filipinas",
    "Polonia",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Rumanía",
    "Rusia",
    "Ruanda",
    "Samoa",
    "San Marino",
    "Arabia Saudita",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leona",
    "Singapur",
    "Eslovaquia",
    "Eslovenia",
    "Islas Salomón",
    "Somalia",
    "Sudáfrica",
    "Corea del Sur",
    "España",
    "Sri Lanka",
    "Sudán",
    "Surinam",
    "Suecia",
    "Suiza",
    "Siria",
    "Taiwán",
    "Tayikistán",
    "Tanzania",
    "Tailandia",
    "Timor Oriental",
    "Togo",
    "Tonga",
    "Túnez",
    "Turquía",
    "Turkmenistán",
    "Tuvalu",
    "Uganda",
    "Ucrania",
    "Emiratos Árabes Unidos",
    "Reino Unido",
    "Estados Unidos",
    "Uruguay",
    "Uzbekistán",
    "Vanuatu",
    "Ciudad del Vaticano",
    "Venezuela",
    "Vietnam",
    "Mundo",
    "Yemen",
    "Zambia",
    "Zimbabue",
  ];

  const codigosPaises = [
    "af",
    "al",
    "dz",
    "ad",
    "ao",
    "ar",
    "am",
    "au",
    "at",
    "az",
    "bs",
    "bh",
    "bd",
    "bb",
    "by",
    "be",
    "bz",
    "bj",
    "bm",
    "bt",
    "bo",
    "ba",
    "bw",
    "br",
    "bn",
    "bg",
    "bf",
    "bi",
    "kh",
    "cm",
    "ca",
    "cv",
    "ky",
    "cf",
    "td",
    "cl",
    "cn",
    "co",
    "km",
    "cg",
    "cr",
    "hr",
    "cu",
    "cy",
    "cz",
    "dk",
    "dj",
    "dm",
    "do",
    "cd",
    "ec",
    "eg",
    "sv",
    "gq",
    "er",
    "ee",
    "sz",
    "et",
    "fj",
    "fi",
    "fr",
    "pf",
    "ga",
    "gm",
    "ge",
    "de",
    "gh",
    "gr",
    "gd",
    "gt",
    "gn",
    "gy",
    "ht",
    "hn",
    "hk",
    "hu",
    "is",
    "in",
    "id",
    "ir",
    "iq",
    "ie",
    "il",
    "it",
    "ci",
    "jm",
    "jp",
    "je",
    "jo",
    "kz",
    "ke",
    "ki",
    "xk",
    "kw",
    "kg",
    "la",
    "lv",
    "lb",
    "ls",
    "lr",
    "ly",
    "li",
    "lt",
    "lu",
    "mo",
    "mk",
    "mg",
    "mw",
    "my",
    "mv",
    "ml",
    "mt",
    "mh",
    "mr",
    "mu",
    "mx",
    "fm",
    "md",
    "mc",
    "mn",
    "me",
    "ma",
    "mz",
    "mm",
    "na",
    "nr",
    "np",
    "nl",
    "nz",
    "ni",
    "ne",
    "ng",
    "kp",
    "no",
    "om",
    "pk",
    "pw",
    "pa",
    "pg",
    "py",
    "pe",
    "ph",
    "pl",
    "pt",
    "pr",
    "qa",
    "ro",
    "ru",
    "rw",
    "ws",
    "sm",
    "sa",
    "sn",
    "rs",
    "sc",
    "sl",
    "sg",
    "sk",
    "si",
    "sb",
    "so",
    "za",
    "kr",
    "es",
    "lk",
    "sd",
    "sr",
    "se",
    "ch",
    "sy",
    "tw",
    "tj",
    "tz",
    "th",
    "tl",
    "tg",
    "to",
    "tn",
    "tr",
    "tm",
    "tv",
    "ug",
    "ua",
    "ae",
    "gb",
    "us",
    "uy",
    "uz",
    "vu",
    "va",
    "ve",
    "vi",
    "wo",
    "ye",
    "zm",
    "zw",
  ];

  return (
    <Form className="d-md-flex justify-content-between p-4 shadow mb-4 bg-primary text-white rounded-1">
      <Container fluid className="p-0">
        <div className="row">
          <div className="col-md-6 d-md-flex flex-md-column align-items-md-center mb-3 mb-md-0">
            <label className="fs-4 mb-2 mb-md-0">Buscar por país: </label>
            <Form.Select className="formSelect" onChange={handleChange} name="pais">
              {nombresPaises.map((pais, i) => (
                <option key={i} value={codigosPaises[i]}>
                  {pais}
                </option>
              ))}
            </Form.Select>
          </div>

          <div className="col-md-6 d-md-flex flex-md-column align-items-md-center">
            <label className="fs-4 mb-2 mb-md-0">Filtrar por categoria: </label>
            <Form.Select className="formSelect" onChange={handleChange} name="categoria">
              {categorias.map((categoria, i) => (
                <option key={i} value={categoria}>
                  {categoriasEsp[i]}
                </option>
              ))}
            </Form.Select>
          </div>
        </div>
      </Container>
    </Form>
  );
};

export default Formulario;
